dist: trusty

language: java

jdk: openjdk8

services: 
  - mongodb
  - rabbitmq

env:

  global:
    - BUILD_FLOW=build

before_install:
  - openssl aes-256-cbc -K $encrypted_93df4cdfe2d3_key -iv $encrypted_93df4cdfe2d3_iv -in maven/settings.xml.enc -out settings.xml -d

install: true

cache:
  directories:
  - $HOME/.m2

before_script:
  - sleep 15
  - ./install-and-configure-Mongo.sh

jobs:

  include:

    - stage: "build"
      script:
      - ./build-ci.sh

stages:
  - name: "build"


