dist: xenial

language: java

jdk: openjdk8

jobs:

  include:

    if: branch = master OR branch =~ /\d*-(.*)$/

    before_install:
      - openssl aes-256-cbc -K $encrypted_93df4cdfe2d3_key -iv $encrypted_93df4cdfe2d3_iv -in maven/settings.xml.enc -out settings.xml -d
      - sudo ./install-and-configure-Mongo.sh
      - sudo ./install-and-configure-RabbitMQ.sh

    install: true

    cache:
      directories:
      - $HOME/.m2

    script:
      - ./build-ci.sh

