dist: trusty

language: java

jdk: openjdk8

services: 
  mongodb
  rabbitmq

jobs:

  include:

    if: branch = master OR branch =~ /\d*-(.*)$/

    before_install:
      - openssl aes-256-cbc -K $encrypted_93df4cdfe2d3_key -iv $encrypted_93df4cdfe2d3_iv -in maven/settings.xml.enc -out settings.xml -d

    install: true

    cache:
      directories:
      - $HOME/.m2

    before_script:
      - sleep 30
      - mongo status
      - mongo --host localhost --eval 'db.createUser({user:"dshuser",pwd:"dsh01!",roles:[ "readWrite"]})' dsh

    script:
      - ./build-ci.sh

